"""
Shared PostgreSQL mapping conventions.

Application tables live in a private schema, never Supabase's auth/storage schemas.
UUIDs and creation timestamps are generated by Postgres, including for SQL writers.
Updates use SQLAlchemy's explicit update default; raw SQL writers must also update
updated_at. Domain tables and their authorization policies arrive in later phases.
"""

from datetime import datetime
from uuid import UUID

from sqlalchemy import DateTime, MetaData, func, text
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

SCHEMA = "hireandtech"
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Metadata boundary consumed by repositories and Alembic autogeneration."""

    metadata = MetaData(schema=SCHEMA, naming_convention=NAMING_CONVENTION)


class IdentityTimestampMixin:
    """Reusable UUID identity and timezone-aware timestamps for domain records."""

    id: Mapped[UUID] = mapped_column(primary_key=True, server_default=text("gen_random_uuid()"))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )
