"""
Resume metadata and structured candidate-profile persistence.

Purpose:
    Represent privately stored resume files and the structured candidate data
    extracted from them.

Responsibilities:
    - Track resume ownership and private storage locations.
    - Track parsing lifecycle and safe failure codes.
    - Store deterministic parser output for future matching.
    - Keep candidate profiles tied to the same owner as their resume.

Does NOT:
    - Upload or download storage objects.
    - Parse PDF files.
    - Perform AI analysis.
    - Match candidates to jobs.

Security:
    Storage object keys are generated by the backend. All repository and service
    operations must scope records to the authenticated profile.
"""

from __future__ import annotations

from datetime import datetime
from decimal import Decimal
from enum import StrEnum
from uuid import UUID

from sqlalchemy import (
    CheckConstraint,
    DateTime,
    Enum,
    ForeignKey,
    ForeignKeyConstraint,
    Index,
    Numeric,
    String,
    Text,
    UniqueConstraint,
    Uuid,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base, IdentityTimestampMixin


class ResumeStatus(StrEnum):
    """Lifecycle states for a privately stored resume."""

    UPLOADED = "uploaded"
    PARSING = "parsing"
    PARSED = "parsed"
    PARSE_FAILED = "parse_failed"
    DELETED = "deleted"


class Resume(IdentityTimestampMixin, Base):
    """Metadata for one privately stored, user-owned resume file."""

    __tablename__ = "resumes"
    __table_args__ = (
        UniqueConstraint(
            "id",
            "owner_profile_id",
            name="uq_resumes_id_owner_profile_id",
        ),
        CheckConstraint(
            "size_bytes > 0",
            name="resume_size_positive",
        ),
        CheckConstraint(
            "char_length(sha256) = 64",
            name="resume_sha256_length",
        ),
        CheckConstraint(
            "content_type = 'application/pdf'",
            name="resume_pdf_content_type",
        ),
        CheckConstraint(
            """
            (status = 'deleted' AND deleted_at IS NOT NULL)
            OR
            (status <> 'deleted' AND deleted_at IS NULL)
            """,
            name="resume_deleted_state_consistent",
        ),
        Index(
            "ix_resumes_owner_created_id",
            "owner_profile_id",
            "created_at",
            "id",
        ),
        Index(
            "ix_resumes_owner_status",
            "owner_profile_id",
            "status",
        ),
        Index(
            "ix_resumes_owner_sha256",
            "owner_profile_id",
            "sha256",
        ),
    )

    owner_profile_id: Mapped[UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey(
            "hireandtech.profiles.id",
            ondelete="RESTRICT",
        ),
        nullable=False,
    )
    original_filename: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
    )
    storage_bucket: Mapped[str] = mapped_column(
        String(63),
        nullable=False,
    )
    storage_object_key: Mapped[str] = mapped_column(
        String(1024),
        nullable=False,
        unique=True,
    )
    content_type: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
    )
    size_bytes: Mapped[int] = mapped_column(
        nullable=False,
    )
    sha256: Mapped[str] = mapped_column(
        String(64),
        nullable=False,
    )
    status: Mapped[ResumeStatus] = mapped_column(
        Enum(
            ResumeStatus,
            name="resume_status",
            native_enum=False,
            create_constraint=True,
            validate_strings=True,
            values_callable=lambda statuses: [status.value for status in statuses],
        ),
        nullable=False,
        default=ResumeStatus.UPLOADED,
        server_default=ResumeStatus.UPLOADED.value,
    )
    parser_version: Mapped[str | None] = mapped_column(
        String(64),
    )
    parse_error_code: Mapped[str | None] = mapped_column(
        String(64),
    )
    deleted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
    )
    candidate_profile: Mapped[CandidateProfile | None] = relationship(
        back_populates="resume",
        uselist=False,
    )


class CandidateProfile(IdentityTimestampMixin, Base):
    """Structured deterministic data extracted from one resume."""

    __tablename__ = "candidate_profiles"
    __table_args__ = (
        ForeignKeyConstraint(
            ["resume_id", "owner_profile_id"],
            [
                "hireandtech.resumes.id",
                "hireandtech.resumes.owner_profile_id",
            ],
            name="fk_candidate_profiles_resume_owner_resumes",
            ondelete="CASCADE",
        ),
        CheckConstraint(
            """
            years_of_experience IS NULL
            OR
            (
                years_of_experience >= 0
                AND years_of_experience <= 80
            )
            """,
            name="candidate_years_of_experience_range",
        ),
        CheckConstraint(
            "jsonb_typeof(skills) = 'array'",
            name="candidate_skills_array",
        ),
        CheckConstraint(
            "jsonb_typeof(employment_history) = 'array'",
            name="candidate_employment_history_array",
        ),
        CheckConstraint(
            "jsonb_typeof(education) = 'array'",
            name="candidate_education_array",
        ),
        CheckConstraint(
            "jsonb_typeof(certifications) = 'array'",
            name="candidate_certifications_array",
        ),
        CheckConstraint(
            "jsonb_typeof(languages) = 'array'",
            name="candidate_languages_array",
        ),
        CheckConstraint(
            "jsonb_typeof(raw_parser_output) = 'object'",
            name="candidate_raw_parser_output_object",
        ),
        Index(
            "ix_candidate_profiles_owner_created_id",
            "owner_profile_id",
            "created_at",
            "id",
        ),
    )

    resume_id: Mapped[UUID] = mapped_column(
        Uuid(as_uuid=True),
        nullable=False,
        unique=True,
    )
    owner_profile_id: Mapped[UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey(
            "hireandtech.profiles.id",
            ondelete="RESTRICT",
        ),
        nullable=False,
    )
    full_name: Mapped[str | None] = mapped_column(String(200))
    email: Mapped[str | None] = mapped_column(String(320))
    phone: Mapped[str | None] = mapped_column(String(64))
    location: Mapped[str | None] = mapped_column(String(200))
    current_title: Mapped[str | None] = mapped_column(String(200))
    professional_summary: Mapped[str | None] = mapped_column(Text)
    years_of_experience: Mapped[Decimal | None] = mapped_column(Numeric(4, 1))
    extracted_text: Mapped[str | None] = mapped_column(Text)
    skills: Mapped[list[str]] = mapped_column(
        JSONB,
        nullable=False,
        default=list,
        server_default=text("'[]'::jsonb"),
    )
    employment_history: Mapped[list[dict[str, object]]] = mapped_column(
        JSONB,
        nullable=False,
        default=list,
        server_default=text("'[]'::jsonb"),
    )
    education: Mapped[list[dict[str, object]]] = mapped_column(
        JSONB,
        nullable=False,
        default=list,
        server_default=text("'[]'::jsonb"),
    )
    certifications: Mapped[list[str]] = mapped_column(
        JSONB,
        nullable=False,
        default=list,
        server_default=text("'[]'::jsonb"),
    )
    languages: Mapped[list[str]] = mapped_column(
        JSONB,
        nullable=False,
        default=list,
        server_default=text("'[]'::jsonb"),
    )
    raw_parser_output: Mapped[dict[str, object]] = mapped_column(
        JSONB,
        nullable=False,
        default=dict,
        server_default=text("'{}'::jsonb"),
    )
    resume: Mapped[Resume] = relationship(back_populates="candidate_profile")
