"""add async search tables

Revision: 7ab1651e6578
Parent: 0007_canonical_jobs
Created: 2026-09-28 04:40:30.451662

Describe data compatibility, ownership restrictions, and downgrade limitations.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "7ab1651e6578"
down_revision: str | None = "0007_canonical_jobs"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the reviewed schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_searches",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("query", sa.String(length=200), nullable=True),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("remote_type", sa.String(length=32), nullable=True),
        sa.Column("job_type", sa.String(length=100), nullable=True),
        sa.Column("experience_min", sa.Integer(), nullable=True),
        sa.Column("experience_max", sa.Integer(), nullable=True),
        sa.Column("requested_limit", sa.Integer(), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("current_stage", sa.String(length=32), nullable=False),
        sa.Column("error_message", sa.String(length=1024), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "progress >= 0 AND progress <= 100", name=op.f("ck_job_searches_chk_progress_range")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["hireandtech.profiles.id"],
            name=op.f("fk_job_searches_user_id_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_searches")),
        schema="hireandtech",
    )
    op.create_index(
        "ix_job_searches_created_at",
        "job_searches",
        ["created_at"],
        unique=False,
        schema="hireandtech",
    )
    op.create_index(
        "ix_job_searches_status", "job_searches", ["status"], unique=False, schema="hireandtech"
    )
    op.create_index(
        "ix_job_searches_user_id", "job_searches", ["user_id"], unique=False, schema="hireandtech"
    )
    op.create_table(
        "job_search_results",
        sa.Column("search_id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("match_score", sa.Float(), nullable=False),
        sa.Column("skills_score", sa.Float(), nullable=False),
        sa.Column("experience_score", sa.Float(), nullable=False),
        sa.Column("location_score", sa.Float(), nullable=False),
        sa.Column("freshness_score", sa.Float(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["hireandtech.jobs.id"],
            name=op.f("fk_job_search_results_job_id_jobs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["search_id"],
            ["hireandtech.job_searches.id"],
            name=op.f("fk_job_search_results_search_id_job_searches"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_search_results")),
        sa.UniqueConstraint("search_id", "job_id", name="uq_job_search_results_search_job"),
        schema="hireandtech",
    )
    op.create_index(
        "ix_job_search_results_rank",
        "job_search_results",
        ["search_id", "rank"],
        unique=False,
        schema="hireandtech",
    )
    op.create_index(
        "ix_job_search_results_search_id",
        "job_search_results",
        ["search_id"],
        unique=False,
        schema="hireandtech",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert only objects owned by this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_job_search_results_search_id", table_name="job_search_results", schema="hireandtech"
    )
    op.drop_index(
        "ix_job_search_results_rank", table_name="job_search_results", schema="hireandtech"
    )
    op.drop_table("job_search_results", schema="hireandtech")
    op.drop_index("ix_job_searches_user_id", table_name="job_searches", schema="hireandtech")
    op.drop_index("ix_job_searches_status", table_name="job_searches", schema="hireandtech")
    op.drop_index("ix_job_searches_created_at", table_name="job_searches", schema="hireandtech")
    op.drop_table("job_searches", schema="hireandtech")
    # ### end Alembic commands ###
